# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('date_create', models.DateTimeField(verbose_name='fecha de creacion')),
                ('password', models.CharField(max_length=6)),
            ],
        ),
    ]
